global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
    - targets: ["prometheus:9090"]

  - job_name: "gateway"
    static_configs:
    - targets: ["gateway:8000"]

  - job_name: "plans-service"
    static_configs:
    - targets: ["plans-service:8005"]

  - job_name: "workouts-service"
    static_configs:
    - targets: ["workouts-service:8004"]

  - job_name: "crm-service"
    static_configs:
    - targets: ["crm-service:8008"]

  - job_name: "exercises-service"
    static_configs:
    - targets: ["exercises-service:8002"]

  - job_name: "accounts-service"
    static_configs:
    - targets: ["accounts-service:8007"]

  - job_name: "agent-service"
    static_configs:
    - targets: ["agent-service:8006"]

  - job_name: "user-max-service"
    static_configs:
    - targets: ["user-max-service:8003"]

  - job_name: "rpe-service"
    static_configs:
    - targets: ["rpe-service:8001"]
